import { db, datePlansTable, checklistItemsTable } from "@workspace/db";
import { logger } from "./logger";

const DATE_PLANS = [
  {
    month: 1,
    monthName: "January",
    theme: "Japan",
    destination: "Tokyo, Japan",
    tagline: "A quiet evening in the lantern-lit alleyways of Tokyo",
    intro: "January calls for warmth and wonder. Transport yourselves to Japan — a culture of extraordinary care, quiet beauty, and food as devotion. Seth will cook, Elana will set the mood, and together you'll explore what it means to be truly present with each other.",
    dinner: { dish: "Miso Ramen with Chashu Pork", cuisine: "Japanese", description: "A rich tonkotsu or miso broth, slow-cooked pork belly, soft-boiled marinated egg, nori, scallions, and bamboo shoots. Comforting, deeply savory, and worth every hour." },
    music: { direction: "Japanese jazz, ambient city sounds, and koto instrumentals", artists: ["Hiromi Uehara", "Nujabes", "Ryo Fukui"], mood: "Quiet, contemplative, and warm — like rain on a Tokyo rooftop" },
    ritual: { title: "The Tea Ceremony", description: "Begin the evening by making two cups of matcha together. One person whisks while the other holds the bowl warm. Bow to each other before drinking. Let this signal that tonight is yours." },
    conversationPrompts: [
      "What's something about your upbringing that still shapes how you love people today?",
      "If we could live anywhere in the world for one year, where would you want to go and why?",
      "What's one thing you want to understand about me that you haven't figured out yet?",
      "What does a perfect ordinary Tuesday look like to you, five years from now?",
      "What's something you've never told anyone that you'd feel safe telling me?",
    ],
    activity: { title: "Write Each Other a Haiku", description: "Each of you writes a haiku — three lines, 5-7-5 syllables — about what this first month of marriage has felt like. Read them to each other slowly. Keep them. Someday you'll want them." },
    localAddOn: { title: "Find a Japanese restaurant for dessert", description: "End the night at a local Japanese spot for mochi ice cream or taiyaki. Or make mochi at home together — it's messy and delightful." },
    effort: "Medium",
    cost: "~$40",
    duration: "3-4 hours",
    scheduledDate: null,
    completed: false,
    completedAt: null,
  },
  {
    month: 2,
    monthName: "February",
    theme: "Morocco",
    destination: "Marrakech, Morocco",
    tagline: "Spice markets, candlelight, and the sound of a medina at dusk",
    intro: "February deserves warmth and color. Morocco offers both in abundance — its food is a love language, its music is ancient and alive, and its rituals invite you to slow down and be fully present. Tonight you are travelers in a souk, and everything smells like cardamom.",
    dinner: { dish: "Lamb Tagine with Preserved Lemon and Olives", cuisine: "Moroccan", description: "Slow-braised lamb with warming spices — cumin, coriander, cinnamon, ginger — served over couscous with a bright lemon-herb finish. Rich, complex, and deeply romantic." },
    music: { direction: "Gnawa trance music, Andalusian classical, and desert blues", artists: ["Oum", "Hassan Hakmoun", "Tinariwen"], mood: "Hypnotic, warm, and ancient — like a fire in an open courtyard" },
    ritual: { title: "Light a Candle, Make a Wish", description: "Before dinner, light a candle together. Each of you speaks one wish for this year of marriage — not out loud if you don't want to. Then light a second candle. Keep them both burning through dinner." },
    conversationPrompts: [
      "What tradition from your family do you most want to carry into ours?",
      "What's something you've changed your mind about since we got together?",
      "When do you feel most seen by me?",
      "What's a dream you've never said aloud to anyone, that you're willing to say now?",
      "If we could do one completely spontaneous thing tomorrow, what would it be?",
    ],
    activity: { title: "Make a Spice Mix Together", description: "Blend your own ras el hanout — find a recipe and combine the spices by hand, talking about what each one smells like and where it takes you. Bottle it and label it with tonight's date." },
    localAddOn: { title: "Find a hammam or Turkish bath", description: "If there's a Turkish bath or hammam spa nearby, book it for after dinner. Relaxation and warmth are on-theme. Or draw a long bath at home and add rose petals." },
    effort: "High",
    cost: "~$55",
    duration: "4-5 hours",
    scheduledDate: null,
    completed: false,
    completedAt: null,
  },
  {
    month: 3,
    monthName: "March",
    theme: "Italy",
    destination: "Amalfi Coast, Italy",
    tagline: "Sunday afternoon on a terrace above the sea",
    intro: "March is for softening. Italy teaches us that the meal is never the point — the people at the table are. Tonight, take all night. Cook slowly. Eat slowly. Let the conversation wander. There's nowhere to be.",
    dinner: { dish: "Handmade Pasta with Clam Sauce (Spaghetti alle Vongole)", cuisine: "Italian", description: "Make fresh pasta together — flour, eggs, and a little elbow grease. Toss in a white wine and garlic clam sauce. Start with bruschetta. Finish with tiramisu. Don't rush any of it." },
    music: { direction: "Italian jazz, bossa nova, and cinematic soundtrack", artists: ["Paolo Conte", "Nino Rota", "Lucio Battisti"], mood: "Breezy and golden — like afternoon light through an open window" },
    ritual: { title: "The First Toast", description: "Pour two glasses before you begin cooking. Look each other in the eye. One of you proposes a toast — not rehearsed, just honest. Whatever comes up is the right thing." },
    conversationPrompts: [
      "What's something that happened in our first month of marriage that surprised you in a good way?",
      "What's your earliest memory of knowing you loved me?",
      "If you could go back and tell your younger self one thing about relationships, what would it be?",
      "What does home mean to you, and are we there yet?",
      "What's one thing I do that makes you feel deeply cared for?",
    ],
    activity: { title: "Make pasta from scratch together", description: "There's something about making pasta by hand that slows everything down. Measure flour on the counter, make a well, crack the eggs, work the dough. It's tactile and meditative and a little chaotic. Perfect." },
    localAddOn: { title: "Find a wine bar for an after-dinner glass", description: "End the night with a glass of something Italian — Barolo, Nero d'Avola, Prosecco. If you can find a wine bar with outdoor seating, even better." },
    effort: "High",
    cost: "~$50",
    duration: "4-5 hours",
    scheduledDate: null,
    completed: false,
    completedAt: null,
  },
  {
    month: 4,
    monthName: "April",
    theme: "India",
    destination: "Jaipur, India",
    tagline: "The Pink City at sunset, color and chaos and quiet temples",
    intro: "April brings color. India offers it in every direction — in the food, in the music, in the textiles, in the way people move through the world. Tonight is loud with flavor and quiet in its ceremony. You'll use your hands. You'll slow down. You'll taste something new.",
    dinner: { dish: "Lamb Biryani with Raita and Naan", cuisine: "Indian (Rajasthani)", description: "Layer basmati rice with slow-cooked spiced lamb, caramelized onions, saffron, and whole spices. Seal the pot. Open it at the table. The smell alone is an occasion." },
    music: { direction: "Rajasthani folk music, Hindustani classical, and modern Bollywood instrumentals", artists: ["Norah Jones (early)", "A.R. Rahman", "Shankar Mahadevan"], mood: "Warm, layered, and joyful — like a courtyard full of light" },
    ritual: { title: "Apply Henna Together", description: "Order henna cones online or find them locally. Draw simple patterns on each other's hands — nothing has to be perfect. Let them dry. Talk about what the symbols mean to you." },
    conversationPrompts: [
      "What's something about Indian or South Asian culture — the food, the art, the philosophy — that's always drawn you in?",
      "When was the last time you felt truly joyful, without any reason to hold back?",
      "What's something you're afraid of that you've never said to me?",
      "How do you want us to handle disagreement differently than you've seen it handled before?",
      "What's a cultural practice or ritual from any tradition that you'd love to bring into our life?",
    ],
    activity: { title: "Watch a Bollywood film together", description: "Pick a Bollywood classic — Dilwale Dulhania Le Jayenge, Lagaan, or something more recent. Don't take it seriously. Sing along if you can. Dance if the moment calls for it." },
    localAddOn: { title: "Visit an Indian restaurant or cultural center", description: "See if there's a nearby Indian grocery where you can source spices and ingredients. Many have recommendations for fresh things you can't find elsewhere." },
    effort: "High",
    cost: "~$45",
    duration: "4-5 hours",
    scheduledDate: null,
    completed: false,
    completedAt: null,
  },
  {
    month: 5,
    monthName: "May",
    theme: "Mexico",
    destination: "Oaxaca, Mexico",
    tagline: "Mezcal and mole, music in the square, the smell of copal",
    intro: "May is for celebration. Oaxaca is one of the world's great food cities — a place where recipes are passed down through generations and every meal is an act of memory. Tonight you eat with intention, and you talk about where you come from.",
    dinner: { dish: "Chicken Mole Negro with Black Beans and Mexican Rice", cuisine: "Oaxacan", description: "The mole is the project — dried chiles, chocolate, spices, and patience. It takes time, which is exactly the point. Make it together over the afternoon so dinner feels like an arrival." },
    music: { direction: "Oaxacan cumbia, son jarocho, and modern Mexican indie", artists: ["Los Cojolites", "Lila Downs", "Natalia Lafourcade"], mood: "Earthy, rhythmic, and alive — like music that comes up through the floor" },
    ritual: { title: "Light Copal Incense", description: "Copal is the incense of Oaxacan ceremony — sacred, woody, ancient. Light a stick before you begin. Let its smoke fill the room. It signals that this is a different kind of evening." },
    conversationPrompts: [
      "What's a family recipe — from anyone in your family — that means something to you?",
      "What's one story from your childhood that you haven't told me yet?",
      "If you could have dinner with anyone who's passed away from your family, who would it be and what would you ask them?",
      "What does generosity mean to you, and who taught it to you?",
      "What part of your cultural identity do you most want our home to reflect?",
    ],
    activity: { title: "Make your own hot sauce", description: "Blend roasted tomatillos, dried chiles, garlic, and cilantro. Season. Bottle it. Write the date on the label. You've made something that will last." },
    localAddOn: { title: "Find a local mezcal or tequila bar", description: "End the night with a proper mezcal tasting — neat, with an orange wedge and sal de gusano if available. Many bars now carry artisanal Mexican spirits." },
    effort: "High",
    cost: "~$50",
    duration: "5-6 hours",
    scheduledDate: null,
    completed: false,
    completedAt: null,
  },
  {
    month: 6,
    monthName: "June",
    theme: "Greece",
    destination: "Santorini, Greece",
    tagline: "Whitewashed walls, Aegean blue, and dinner as the sun goes down",
    intro: "June belongs to the Mediterranean. Greece is warmth and simplicity — olive oil and sea salt and lemon and good company. Tonight is slower than you think it needs to be, and that's the whole point. You'll eat outside if you can. You'll linger.",
    dinner: { dish: "Whole Roasted Fish with Lemon, Olive Oil, and Herbs", cuisine: "Greek", description: "A whole sea bass or branzino roasted over sliced fennel and lemon, dressed simply with good olive oil and fresh herbs. Serve with Greek salad and tzatziki. Open a bottle of Assyrtiko." },
    music: { direction: "Greek laïká, rebetiko, and Aegean folk", artists: ["Nikos Papazoglou", "George Dalaras", "Savina Yannatou"], mood: "Melancholic and warm — the sound of the sea at dusk" },
    ritual: { title: "Olive Oil Toast", description: "Before dinner, pour a small dish of good olive oil. Dip bread into it together. One of you says what you're grateful for this month. The other says one thing they're looking forward to." },
    conversationPrompts: [
      "What does simplicity mean to you in the context of a life well-lived?",
      "What's a place you've been to that changed how you see the world?",
      "If we had a whole week with nothing scheduled, how would you want to spend it?",
      "What's something about how I see the world that you find genuinely surprising or admirable?",
      "What kind of old people do you want us to be?",
    ],
    activity: { title: "Learn a few words of Greek together", description: "Spend 20 minutes learning some basics — how to say cheers (yamas!), I love you (s'agapo), and thank you (efharisto). Then use them throughout dinner." },
    localAddOn: { title: "Find a rooftop or outdoor terrace for a drink", description: "If you can find somewhere with a view — even a rooftop bar or a park with a skyline — go there for a drink after dinner. A view makes everything feel more expansive." },
    effort: "Medium",
    cost: "~$40",
    duration: "3-4 hours",
    scheduledDate: null,
    completed: false,
    completedAt: null,
  },
  {
    month: 7,
    monthName: "July",
    theme: "Ethiopia",
    destination: "Addis Ababa, Ethiopia",
    tagline: "Eating with your hands and talking about everything at once",
    intro: "July is for something completely different. Ethiopian food is one of the most communal, abundant, and sensory dining experiences in the world — you eat from the same plate, you share everything, you feed each other. There's a word for that intimacy: gursha. Tonight you practice it.",
    dinner: { dish: "Ethiopian Feast — Doro Wat, Misir, and Gomen on Injera", cuisine: "Ethiopian", description: "Make a full spread: spiced chicken stew (doro wat), red lentils (misir), braised greens (gomen), served on a large sheet of injera. No utensils. Tear the bread. Scoop with your hands. Feed each other." },
    music: { direction: "Ethiopian jazz, Amharic pop, and Ethio-groove", artists: ["Mulatu Astatke", "Mahmoud Ahmed", "Aster Aweke"], mood: "Warm, complex, and completely alive — music that tells you something ancient is still present" },
    ritual: { title: "The Gursha", description: "In Ethiopian culture, gursha is the act of feeding someone from your hand as an expression of love and respect. Feed each other one bite at the beginning of the meal. Do it slowly. Make eye contact." },
    conversationPrompts: [
      "What's something about how your family expressed love that you want to carry forward?",
      "What does it mean to you to be truly generous with another person?",
      "What's an assumption you've made about me that turned out to be wrong?",
      "What's something that consistently brings you joy that has nothing to do with achievement?",
      "What do you think we'll be talking about at this same table in 30 years?",
    ],
    activity: { title: "Learn the Ethiopian coffee ceremony", description: "Ethiopia is the birthplace of coffee. Look up the traditional ceremony — the roasting, the grinding, the multiple rounds. Make coffee together slowly and deliberately. Talk about what rituals mean in your life." },
    localAddOn: { title: "Find an Ethiopian restaurant", description: "Ethiopian food is best when someone else made the injera. Find a good local spot for a second dinner or a dessert course." },
    effort: "Medium",
    cost: "~$35",
    duration: "3-4 hours",
    scheduledDate: null,
    completed: false,
    completedAt: null,
  },
  {
    month: 8,
    monthName: "August",
    theme: "Thailand",
    destination: "Chiang Mai, Thailand",
    tagline: "Night markets, temple bells, and the heat of bird's eye chiles",
    intro: "August is for adventure and heat. Thailand's food is a symphony — sweet, sour, salty, spicy, all at once. The culture is gentle and precise and holds enormous depth. Tonight you're at a northern Thai night market, and everything smells extraordinary.",
    dinner: { dish: "Northern Thai Larb Moo with Sticky Rice and Papaya Salad", cuisine: "Northern Thai", description: "Larb is a minced meat salad with toasted rice powder, fish sauce, lime, chilies, and fresh herbs. Serve with sticky rice (glutinous rice steamed in a bamboo basket) and green papaya salad. Eat with your hands." },
    music: { direction: "Thai classical music, mor lam, and contemporary Thai pop", artists: ["Carabao", "Bird Thongchai", "Phum Viphurit"], mood: "Bright, energetic, and layered — like a city that never quite quiets down" },
    ritual: { title: "Wai Each Other", description: "The Thai greeting is a bow with hands pressed together in prayer position. At the start of the evening, wai each other — a small bow, hands at heart center. It's a gesture of respect and presence." },
    conversationPrompts: [
      "What's something about Thai Buddhist culture — mindfulness, impermanence, nonattachment — that resonates with you?",
      "What's a belief you hold about the world that most people in your life would find surprising?",
      "When do you feel most like yourself?",
      "What's a fear you've been carrying that you're ready to put down?",
      "What would you do with your life if you knew you couldn't fail?",
    ],
    activity: { title: "Make a Thai iced tea together", description: "Thai iced tea is a beautiful orange color and deeply satisfying. Brew the tea, add condensed milk, pour over ice. Make two and clink glasses. It's simple and feels like a treat." },
    localAddOn: { title: "Find a Thai massage studio", description: "Thai massage is one of the world's great physical arts. If there's a reputable studio nearby, book a couples session after dinner. You'll feel like new people." },
    effort: "Medium",
    cost: "~$35",
    duration: "3-4 hours",
    scheduledDate: null,
    completed: false,
    completedAt: null,
  },
  {
    month: 9,
    monthName: "September",
    theme: "France",
    destination: "Paris, France",
    tagline: "Rue de Buci on a Saturday evening, wine in hand, nowhere to be",
    intro: "September calls for elegance and ease. France built an entire civilization around the idea that pleasure — in food, in company, in conversation — is a serious thing. Tonight you take it seriously. You dress slightly nicer than you need to. You open a good bottle. You don't rush.",
    dinner: { dish: "Roast Chicken with Herbs de Provence, Roasted Vegetables, and Beurre Blanc", cuisine: "French", description: "A simple, perfect roast chicken — the French obsession, and for good reason. Trussed, dried, and roasted at high heat until the skin shatters. Served with a white wine butter sauce and roasted root vegetables." },
    music: { direction: "French chanson, bossa nova interpretations, and late-night jazz", artists: ["Édith Piaf", "Serge Gainsbourg", "Charlotte Gainsbourg"], mood: "Romantic and slightly melancholic — the most beautiful kind" },
    ritual: { title: "The Aperitif Hour", description: "Pour two glasses of Kir — white wine with a splash of cassis. Sit together before any cooking happens. No phones. No plans. Just drink and talk. The French call this l'apéro, and it's sacred." },
    conversationPrompts: [
      "What's something about the French approach to life — pleasure, leisure, beauty — that you want more of in ours?",
      "What's the most romantic thing anyone has ever done for you?",
      "What does luxury mean to you? Is it a feeling? A thing? A way of time?",
      "What's a part of your personality that you've been holding back in our relationship?",
      "If we had a home in Paris for a summer, what would our days look like?",
    ],
    activity: { title: "Make crêpes together", description: "Crêpes are both simple and endlessly satisfying — thin, golden, filled with Nutella and banana or savory with ham and cheese. Make a batch and eat them standing at the stove, taking turns." },
    localAddOn: { title: "Find a French bistro or wine bar", description: "After dinner, find a local wine bar or French bistro for a digestif — Calvados, Armagnac, or a final glass of Burgundy. Sit close together." },
    effort: "Medium",
    cost: "~$45",
    duration: "3-4 hours",
    scheduledDate: null,
    completed: false,
    completedAt: null,
  },
  {
    month: 10,
    monthName: "October",
    theme: "Lebanon",
    destination: "Beirut, Lebanon",
    tagline: "A city of contradictions, extraordinary food, and irrepressible life",
    intro: "October is for depth. Beirut is one of the most complex, resilient, and culturally rich cities in the world — its food tells stories of countless civilizations, its music bridges East and West, and its people hold onto beauty even in difficult times. Tonight you learn from that.",
    dinner: { dish: "Lebanese Mezze Feast", cuisine: "Lebanese", description: "Hummus (make it from scratch), baba ganoush, fattoush salad, kibbeh, lamb kofta, and warm pita from the oven. A mezze meal is made for sharing — dozens of small dishes, none of them the main course, all of them together the point." },
    music: { direction: "Fairuz, Lebanese jazz, and contemporary Beirut indie", artists: ["Fairuz", "Marcel Khalife", "Mashrou' Leila"], mood: "Bittersweet, beautiful, and surprisingly warm — music that holds sorrow and joy at the same time" },
    ritual: { title: "The Orange Blossom Welcome", description: "Lebanese hospitality often begins with orange blossom water. Add a few drops to sparkling water in two glasses and sip together before dinner. Welcome each other to the evening." },
    conversationPrompts: [
      "What's a belief about yourself that you've held for a long time that you're not sure is still true?",
      "When have you felt most proud of how I handled something?",
      "What's a difficult thing we've been avoiding talking about that we should probably talk about?",
      "What does resilience look like to you in a marriage?",
      "What's something you want to forgive yourself for?",
    ],
    activity: { title: "Make knafeh together", description: "Knafeh is a Lebanese cheese pastry soaked in rose water syrup — absolutely extraordinary. It requires some effort but the reward is worth it. If you can't find the ingredients, make baklava instead." },
    localAddOn: { title: "Find a Lebanese or Middle Eastern restaurant", description: "Many Lebanese restaurants have live music on weekends. If yours does, plan the reservation accordingly." },
    effort: "High",
    cost: "~$50",
    duration: "4-5 hours",
    scheduledDate: null,
    completed: false,
    completedAt: null,
  },
  {
    month: 11,
    monthName: "November",
    theme: "Peru",
    destination: "Lima, Peru",
    tagline: "The city that quietly became one of the world's great food capitals",
    intro: "November calls for something bold. Peru's food scene is one of the world's most exciting — built on indigenous ingredients, Japanese technique, and West African soul. Lima is a city that surprised the world by being extraordinary. Tonight, let it surprise you.",
    dinner: { dish: "Peruvian Ceviche and Lomo Saltado", cuisine: "Peruvian (Nikkei)", description: "Start with a bright, acidic ceviche — fresh fish cured in lime juice with ají amarillo, red onion, and cilantro. Then make lomo saltado, the Peruvian-Chinese stir-fry of beef, tomatoes, and French fries. Two dishes. Two stories." },
    music: { direction: "Afro-Peruvian music, Andean folk, and Lima jazz", artists: ["Chabuca Granda", "Susana Baca", "Gian Marco"], mood: "Layered, joyful, and complex — the sound of a city that absorbed everything and made it its own" },
    ritual: { title: "The Pisco Sour Toast", description: "Make two pisco sours — pisco, lime juice, simple syrup, egg white, Angostura bitters. Shake hard. Pour carefully. Toast to one thing you've built together in the first eleven months." },
    conversationPrompts: [
      "What's something we've built together this year that you didn't expect?",
      "What has been the hardest moment so far, and what did it teach you?",
      "What's a part of yourself you feel you've found — or rediscovered — since we got married?",
      "What's one thing you want to do differently next year?",
      "What's the best thing about being married to me, in your honest opinion?",
    ],
    activity: { title: "Design our first anniversary date", description: "Spend part of the evening planning month 12 together — your one-year celebration. Where do you want to go? What do you want to do? What does the perfect anniversary look like? Make a plan, even if it's rough." },
    localAddOn: { title: "Find a Peruvian restaurant", description: "Peruvian food has had a global moment — there may be a restaurant nearby. If so, go for ceviche at the bar." },
    effort: "Medium",
    cost: "~$45",
    duration: "3-4 hours",
    scheduledDate: null,
    completed: false,
    completedAt: null,
  },
  {
    month: 12,
    monthName: "December",
    theme: "Anywhere You Want",
    destination: "Your First Anniversary",
    tagline: "You made it. A whole year. Celebrate like you mean it.",
    intro: "December is yours to define. This is month twelve — your first anniversary date night. You've traveled the world together over the last year, through kitchens and playlists and conversations that went places you didn't expect. Tonight you celebrate that. Go back to the destination that meant the most to you, or choose somewhere entirely new. The world is yours.",
    dinner: { dish: "Your Favorite Dish from the Year", cuisine: "Wherever your heart is", description: "Cook the dish that meant the most to you this year — or order from the restaurant that represents your favorite memory. This meal is a review of the journey. Let it be whatever it needs to be." },
    music: { direction: "A playlist you build together tonight", artists: ["Every artist you fell in love with this year"], mood: "Everything you felt — all of it, at once" },
    ritual: { title: "Read Your Letters to Each Other", description: "On month 1, you were asked to write each other a haiku. Tonight, write each other a longer letter — one page, unsealed. Write about who you've been to each other, what you've learned, what you're carrying into year two. Read them aloud." },
    conversationPrompts: [
      "What surprised you most about the first year of marriage?",
      "What's the most meaningful conversation we had this year?",
      "What do you know about me now that you couldn't have known a year ago?",
      "What's one thing you want to promise me for year two?",
      "What does this marriage mean to you, in the simplest, most honest words you have?",
    ],
    activity: { title: "Make a time capsule", description: "Collect items from the year — a restaurant receipt, a photo, a ticket stub, a small note. Seal them in an envelope together. Write a date on the outside — maybe year 5, maybe year 10 — when you'll open it together." },
    localAddOn: { title: "Go somewhere that matters", description: "Revisit a place from your first year — the spot where you had your first date as a married couple, or somewhere that felt significant. Walk. Talk. Remember." },
    effort: "Whatever you want",
    cost: "Whatever it's worth",
    duration: "As long as you need",
    scheduledDate: null,
    completed: false,
    completedAt: null,
  },
];

const CHECKLIST_ITEMS: { month: number; label: string }[] = [
  // Month 1 - Japan
  { month: 1, label: "Source Japanese ingredients: miso paste, chashu pork, ramen noodles, soft-boil eggs" },
  { month: 1, label: "Order or find matcha and a whisk for the tea ceremony" },
  { month: 1, label: "Download Japanese jazz playlist for Elana to build on" },
  { month: 1, label: "Clear the table and set it simply — less is more tonight" },
  { month: 1, label: "Have paper and pens ready for the haiku activity" },

  // Month 2 - Morocco
  { month: 2, label: "Source lamb shoulder, preserved lemons, and Moroccan spices" },
  { month: 2, label: "Order copal incense (or use candles as a substitute)" },
  { month: 2, label: "Buy two pillar candles for the lighting ritual" },
  { month: 2, label: "Source ras el hanout spices for the blending activity" },
  { month: 2, label: "Set a warm, candlelit table — think textiles, low light" },

  // Month 3 - Italy
  { month: 3, label: "Buy pasta flour (00 flour) and fresh clams or canned clams" },
  { month: 3, label: "Source a bottle of Italian white wine (Pinot Grigio or Vermentino)" },
  { month: 3, label: "Find mascarpone and espresso for the tiramisu" },
  { month: 3, label: "Clear space to roll pasta — you'll need the counter" },
  { month: 3, label: "Queue up Italian music for Elana to build from" },

  // Month 4 - India
  { month: 4, label: "Source basmati rice, whole spices, and lamb or chicken" },
  { month: 4, label: "Order henna cones online (or find at a local Indian grocery)" },
  { month: 4, label: "Find saffron — just a small amount is needed" },
  { month: 4, label: "Pick a Bollywood film to watch together after dinner" },
  { month: 4, label: "Set a colorful table — India loves color" },

  // Month 5 - Mexico
  { month: 5, label: "Source dried chiles: ancho, mulato, pasilla, and chipotle" },
  { month: 5, label: "Find Mexican chocolate (Ibarra or Abuelita)" },
  { month: 5, label: "Order or find copal incense" },
  { month: 5, label: "Source hot sauce ingredients: tomatillos, dried chiles, garlic" },
  { month: 5, label: "Find small bottles or jars to store the homemade hot sauce" },

  // Month 6 - Greece
  { month: 6, label: "Buy a whole fish (branzino or sea bass) from a good fishmonger" },
  { month: 6, label: "Source a bottle of Greek wine — Assyrtiko if you can find it" },
  { month: 6, label: "Buy good olive oil — splurge a little, it matters tonight" },
  { month: 6, label: "Find Greek yogurt, cucumber, and dill for tzatziki" },
  { month: 6, label: "If possible, plan to eat outside or near an open window" },

  // Month 7 - Ethiopia
  { month: 7, label: "Source berbere spice blend and teff flour (for injera) or buy injera pre-made" },
  { month: 7, label: "Find a recipe for doro wat and begin marinating chicken the night before" },
  { month: 7, label: "Order Ethiopian coffee beans for the ceremony" },
  { month: 7, label: "Clear the dining table — you'll eat from one large shared plate" },
  { month: 7, label: "Have a bowl of water and a small towel for washing hands at the table" },

  // Month 8 - Thailand
  { month: 8, label: "Source fish sauce, lime leaves, lemongrass, and bird's eye chiles" },
  { month: 8, label: "Find glutinous rice for sticky rice (or use store-bought)" },
  { month: 8, label: "Buy Thai iced tea mix (or loose Ceylonese tea and condensed milk)" },
  { month: 8, label: "Download a Thai massage tutorial for a home version" },
  { month: 8, label: "Source green papaya or substitute with green mango" },

  // Month 9 - France
  { month: 9, label: "Buy the best chicken you can find — this dish lives or dies by the bird" },
  { month: 9, label: "Source herbes de Provence, a good French butter, and crème fraîche" },
  { month: 9, label: "Open a bottle of good French white or Burgundy" },
  { month: 9, label: "Buy cassis for the Kir aperitif" },
  { month: 9, label: "Set the table elegantly — linen if you have it, candles always" },

  // Month 10 - Lebanon
  { month: 10, label: "Soak chickpeas overnight for homemade hummus" },
  { month: 10, label: "Source tahini, za'atar, sumac, and pomegranate molasses" },
  { month: 10, label: "Find orange blossom water for the welcome ritual" },
  { month: 10, label: "Make or buy pita bread — fresh is transformative" },
  { month: 10, label: "Source knafeh ingredients: shredded kataifi pastry, akkawi cheese" },

  // Month 11 - Peru
  { month: 11, label: "Source ají amarillo paste — look in Latin grocery stores" },
  { month: 11, label: "Buy the freshest fish available for ceviche (ask your fishmonger)" },
  { month: 11, label: "Source pisco for the cocktail ritual (or use any good brandy)" },
  { month: 11, label: "Have lime juice ready — ceviche needs a lot" },
  { month: 11, label: "Start planning month 12 — anniversary dinner location or home theme" },

  // Month 12 - Anniversary
  { month: 12, label: "Write your anniversary letter — one page, honest and unhurried" },
  { month: 12, label: "Gather items for the time capsule: photos, receipts, notes from the year" },
  { month: 12, label: "Cook the dish that meant the most to you this year" },
  { month: 12, label: "Find a special bottle to open — save it for tonight" },
  { month: 12, label: "Plan where you want to go to mark the occasion — somewhere that matters" },
];

export async function seed() {
  logger.info("Seeding date plans...");

  const existing = await db.select().from(datePlansTable);
  if (existing.length > 0) {
    logger.info("Date plans already seeded, skipping");
    return;
  }

  await db.insert(datePlansTable).values(DATE_PLANS);
  logger.info("Seeded 12 date plans");

  await db.insert(checklistItemsTable).values(CHECKLIST_ITEMS);
  logger.info(`Seeded ${CHECKLIST_ITEMS.length} checklist items`);
}
